name: CI/CD Pipeline

on:
  push:
    tags: ['v*']

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  AWS_REGION: "ap-southeast-1"
  IMAGE_VERSION: ${{ secrets.ECR_REGISTRY }}/${{ github.event.repository.name }}:${{ github.ref_name }}_${{ github.sha }}
  SNYKSCAN_REPORT: "snyk_scan_${{ github.event.repository.name }}_${{ github.ref_name }}_${{ github.sha }}_report"
  TRIVYFS_REPORT: "trivy_fs_scan_${{ github.event.repository.name }}_${{ github.ref_name }}_${{ github.sha }}_report"
  TRIVY_IMAGE_REPORT: "security_scan_image_${{ github.event.repository.name }}_${{ github.ref_name }}_${{ github.sha }}_report"
  ARACHNI_WEBSITE_REPORT: "arachni_scan_website_${{ github.event.repository.name }}_${{ github.ref_name }}_${{ github.sha }}_report"
  ZAP_WEBSITE_REPORT: "zap_scan_website_${{ github.event.repository.name }}_${{ github.ref_name }}_${{ github.sha }}_report"

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted
    environment: production 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Amazone ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Build and Push Docker image on ECR
      run: |
        docker build --network=host -t ${{ env.IMAGE_VERSION }} .
        docker images | grep ${{ github.event.repository.name }}
        docker push ${{ env.IMAGE_VERSION }}

  # snyk-scan:
  #   name: Snyk Source Code Scan
  #   runs-on: self-hosted
  #   needs: build
  #   environment: production
    
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Build Snyk scanner
  #     run: |
  #       docker build --rm --network host \
  #         --build-arg SNYK_AUTH_TOKEN=${{ secrets.SNYK_TOKEN }} \
  #         --build-arg OUTPUT_FILENAME=${{ env.SNYKSCAN_REPORT }} \
  #         -t ${{ env.SNYKSCAN_REPORT }} \
  #         -f Dockerfile-snyk .

  #   - name: Extract Snyk report
  #     run: |
  #       docker create --name ${{ env.SNYKSCAN_REPORT }} ${{ env.SNYKSCAN_REPORT }}
  #       docker cp ${{ env.SNYKSCAN_REPORT }}:/app/${{ env.SNYKSCAN_REPORT }}.html .
  #       docker rm ${{ env.SNYKSCAN_REPORT }}
  #       docker rmi ${{ env.SNYKSCAN_REPORT }}

  #   - name: Upload Snyk report
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: snyk-scan-report
  #       path: ${{ env.SNYKSCAN_REPORT }}.html
  #       retention-days: 1

  trivy-fs-scan:
    name: Trivy Source Code Scan
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy filesystem scan
      run: |
        docker run --rm \
          -v $PWD:/${{ github.event.repository.name }} \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:0.69.3 fs /${{ github.event.repository.name }} \
          --severity HIGH,CRITICAL \
          --format template \
          --template "@contrib/html.tpl" \
          --output /${{ github.event.repository.name }}/${{ env.TRIVYFS_REPORT }}.html

    - name: Upload Trivy FS report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-fs-report
        path: ${{ env.TRIVYFS_REPORT }}.html
        retention-days: 1

  trivy-image-scan:
    name: Trivy Image Security Scan
    runs-on: self-hosted
    needs: [build, trivy-fs-scan]
    
    steps:
    - name: Clean Trivy cache
      run: |
        docker run --rm \
          -v $(pwd):/${{ github.event.repository.name }} \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:0.69.3 clean --all

    - name: Scan Docker image with Trivy
      run: |
        docker run --rm \
          -v $(pwd):/${{ github.event.repository.name }} \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:0.69.3 image \
          --format template \
          --template "@contrib/html.tpl" \
          --output /${{ github.event.repository.name }}/${{ env.TRIVY_IMAGE_REPORT }}.html \
          ${{ env.IMAGE_VERSION }}

    - name: Upload Trivy image report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-image-report
        path: ${{ env.TRIVY_IMAGE_REPORT }}.html
        retention-days: 1

  deploy:
    name: Deploy Application
    runs-on: self-hosted
    needs: [build, trivy-fs-scan, trivy-image-scan]
    environment: production  
    
    steps:
    - name: Deploy on AWS with CloudWatch Logs
      run: |
        sudo su ${{ secrets.USER_PROJECT }}p '
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
 
          docker stop ${{ github.event.repository.name }} || true
          docker rm ${{ github.event.repository.name }} || true
          docker pull ${{ env.IMAGE_VERSION }}
          docker run --name ${{ github.event.repository.name }} \
          -e "ConnectionStrings__UserAppCon=${{ secrets.DB_CONNECTION_STRING }}" \
          -dp ${{ secrets.BE_PORT }} \
          --log-driver=awslogs \
          --log-opt awslogs-region=${{ env.AWS_REGION }} \
          --log-opt awslogs-group=/ec2/${{ github.event.repository.name }} \
          --log-opt awslogs-create-group=true \
          ${{ env.IMAGE_VERSION }} 

          docker image prune -f
        '

  arachni-website-scan:
    name: Arachni Website Security Scan
    runs-on: self-hosted
    needs: deploy
    environment: production 
    
    steps:
    - name: Prepare temp folder
      run: mkdir -p arachni-temp
      
    - name: Run Arachni scan
      run: |
        docker run --rm \
          -v $(pwd)/arachni-temp/:/arachni-temp/ \
          arachni/arachni:latest \
          /usr/local/arachni/bin/arachni \
          --output-verbose \
          --scope-include-subdomains \
          "${{ secrets.URL_BE }}" \
          --report-save-path=/arachni-temp/${{ env.ARACHNI_WEBSITE_REPORT }}.afr

    - name: Generate Arachni HTML report
      run: |
        docker run --rm \
          -v $(pwd)/arachni-temp/:/arachni-temp/ \
          arachni/arachni:latest \
          /usr/local/arachni/bin/arachni_reporter \
          /arachni-temp/${{ env.ARACHNI_WEBSITE_REPORT }}.afr \
          --reporter=html:outfile=/arachni-temp/${{ env.ARACHNI_WEBSITE_REPORT }}.html.zip
        sudo chown -R $(whoami):$(whoami) ./arachni-temp/

    - name: Upload Arachni report
      uses: actions/upload-artifact@v4
      with:
        name: arachni-website-report
        path: arachni-temp/${{ env.ARACHNI_WEBSITE_REPORT }}.html.zip
        retention-days: 1

  zap-website-scan:
    name: ZAP Website Security Scan
    runs-on: self-hosted
    needs: deploy
    environment: production 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run ZAP baseline scan
      continue-on-error: true
      run: |
        docker run --rm \
          -u root \
          -v $(pwd):/zap/wrk/:rw \
          zaproxy/zap-stable \
          zap-baseline.py \
          -t "${{ secrets.URL_BE }}" \
          -r "${{ env.ZAP_WEBSITE_REPORT }}.html" \
          --autooff || true
        sudo chown -R $(whoami):$(whoami) "${{ env.ZAP_WEBSITE_REPORT }}.html"

    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
        name: zap-website-report
        path: ${{ env.ZAP_WEBSITE_REPORT }}.html
        retention-days: 1

  check-logs:
    name: Check Application Logs
    runs-on: self-hosted
    needs: deploy

    steps:
    - name: Check Application Logs
      run: |
        docker logs ${{ github.event.repository.name }} --tail 50
